# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PokeClub' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PokeClub
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'
end


